### ISSUE TITLE
[Feature] Find octants by bounding box

### ISSUE THREAD

**Issue by LexSong** [retroplasma/earth-reverse-engineering#25]
I add a python script to find overlapping octants by bounding box, instead of single point:
https://github.com/LexSong/earth-reverse-engineering/tree/find_overlaps

The script will stop early if it finds too many octants in the same level, so it can be used to dump large area. I don't know javascript well enough to add the function to the main repo.

Hopefully people will find this useful.

Example output:
```
> python find_overlaps.py 37.420626 37.419714 -122.085045 -122.083275
LatLonBox(north=37.420626, south=37.419714, west=-122.085045, east=-122.083275)
[Octant level 1]
2
[Octant level 2]
20
[Octant level 3]
205
[Octant level 4]
2052
[Octant level 5]
20527
[Octant level 6]
205270
[Octant level 7]
2052706
[Octant level 8]
20527061
[Octant level 9]
205270616
[Octant level 10]
2052706160
[Octant level 11]
20527061605
[Octant level 12]
205270616052
[Octant level 13]
2052706160527
[Octant level 14]
20527061605273
[Octant level 15]
205270616052735
[Octant level 16]
2052706160527351
[Octant level 17]
20527061605273514
[Octant level 18]
205270616052735141
205270616052735140
[Octant level 19]
2052706160527351416
2052706160527351417
2052706160527351415
2052706160527351414
2052706160527351405
2052706160527351407
2052706160527351406
2052706160527351404
[Octant level 20]
20527061605273514162
20527061605273514160
....
```

**Comment by retroplasma** [comment]
Very nice! I would link to it in the README if you don't mind. We could also merge it if we document the pip goog proto dependency; at this point the repo is just a collection of scripts anyway.

**Comment by Rakiah** [comment]
Maybe we could use http://www.transcrypt.org to transpile python into JavaScript to have a single dependency ?

**Comment by felixgeen** [comment]
Hi there, i've been trying to get this to work but when I run the python script I get this error: Traceback (most recent call last):
  File "find_overlaps.py", line 4, in <module>
    from proto.BulkOrPlanetoid_pb2 import BulkOrPlanetoid
  File "C:\Users\snah\Documents\earth-reverse-engineering-master\proto\BulkOrPlanetoid_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'

any idea what might be going wrong? Thank you!

**Comment by LexSong** [comment]
> from google.protobuf import descriptor as _descriptor
> ModuleNotFoundError: No module named 'google'
> 
> any idea what might be going wrong? Thank you!

you need to install [google protobuf](https://pypi.org/project/protobuf/)

**Comment by mitchaiet** [comment]
What's the best way to download + merge multiple octants?

I used the script to return this list of a large area: 

2053525261517151 2053525261517153 2053525261517152 2053525261517150 2053525261517141 2053525261517143 2053525261517161 2053525261517170 2053525261517171 2053525261517155 2053525261517157 2053525261517156 2053525261517154 2053525261517145 2053525261517147 2053525261517165 2053525261517174 2053525261517175 2053525270406061 2053525270406060 2053525270406042 2053525270406043 2053525270406041 2053525270406040 2053525270406065 2053525270406064 2053525270406046 2053525270406047 2053525270406045 2053525270406044

Ran: Mitchs-MBP:earth-reverse-engineering-master Mitch$ node dump_obj.js 2053525261517151 2053525261517153 2053525261517152 2053525261517150 2053525261517141 2053525261517143 2053525261517161 2053525261517170 2053525261517171 2053525261517155 2053525261517157 2053525261517156 2053525261517154 2053525261517145 2053525261517147 2053525261517165 2053525261517174 2053525261517175 2053525270406061 2053525270406060 2053525270406042 2053525270406043 2053525270406041 2053525270406040 2053525270406065 2053525270406064 2053525270406046 2053525270406047 2053525270406045 2053525270406044 20


Got the following error: 
Error: ENAMETOOLONG: name too long, unlink 'downloaded_files/obj/2053525261517151+2053525261517153+2053525261517152+2053525261517150+2053525261517141+2053525261517143+2053525261517161+2053525261517170+2053525261517171+2053525261517155+2053525261517157+2053525261517156+2053525261517154+2053525261517145+2053525261517147+2053525261517165+2053525261517174+2053525261517175+2053525270406061+2053525270406060+2053525270406042+2053525270406043+2053525270406041+2053525270406040+2053525270406065+2053525270406064+2053525270406046+2053525270406047+2053525270406045+2053525270406044-20-852'
    at Object.unlinkSync (fs.js:976:3)
    at Object.rimrafSync [as removeSync] (/Users/Mitch/Downloads/earth-reverse-engineering-master/node_modules/fs-extra/lib/remove/rimraf.js:254:15)
    at run (/Users/Mitch/Downloads/earth-reverse-engineering-master/dump_obj.js:29:6)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async program (/Users/Mitch/Downloads/earth-reverse-engineering-master/dump_obj.js:350:2) {
  errno: -63,
  syscall: 'unlink',
  code: 'ENAMETOOLONG',
  path: 'downloaded_files/obj/2053525261517151+2053525261517153+2053525261517152+2053525261517150+2053525261517141+2053525261517143+2053525261517161+2053525261517170+2053525261517171+2053525261517155+2053525261517157+2053525261517156+2053525261517154+2053525261517145+2053525261517147+2053525261517165+2053525261517174+2053525261517175+2053525270406061+2053525270406060+2053525270406042+2053525270406043+2053525270406041+2053525270406040+2053525270406065+2053525270406064+2053525270406046+2053525270406047+2053525270406045+2053525270406044-20-852'

**Comment by psociety** [comment]
@LexSong What website do you recommend to get the bounding box? I tried using coords from:
http://bboxfinder.com/ and your  py output is empty:
```bash
python3.6 find_overlaps.py 41.340216 2.102509 41.465113 2.270393
LatLonBox(north=41.340216, south=2.102509, west=41.465113, east=2.270393)
[Octant level 1]
[Octant level 2]
[Octant level 3]
[Octant level 4]
[Octant level 5]
[Octant level 6]
[Octant level 7]
[Octant level 8]
[Octant level 9]
[Octant level 10]
[Octant level 11]
[Octant level 12]
[Octant level 13]
[Octant level 14]
[Octant level 15]
[Octant level 16]
[Octant level 17]
[Octant level 18]
[Octant level 19]
[Octant level 20]
```

**Comment by Rakiah** [comment]
@psociety you've mixed the number around, lexsong's script uses north then south then west then east, not north west south east

**Comment by psociety** [comment]
@Rakiah oh, i tried recombining them yet i got the same result:
```bash
 python3.6 find_overlaps.py 41.340216 41.465113 2.102509 2.270393
LatLonBox(north=41.340216, south=41.465113, west=2.102509, east=2.270393)
[Octant level 1]
[Octant level 2]
[Octant level 3]
[Octant level 4]
[Octant level 5]
[Octant level 6]
[Octant level 7]
[Octant level 8]
[Octant level 9]
[Octant level 10]
[Octant level 11]
[Octant level 12]
[Octant level 13]
[Octant level 14]
[Octant level 15]
[Octant level 16]
[Octant level 17]
[Octant level 18]
[Octant level 19]
[Octant level 20]
```

**Comment by LexSong** [comment]
I assume that the north latitude should larger than south latitude?
Try `41.465113 41.340216 2.102509 2.270393`

**Comment by psociety** [comment]
@LexSong you're right now it does throw octants up to level 13 :)
Sorry for littering the thread.

**Comment by bhaktatejas922** [comment]
Hey, total beginner to this stuff. Could someone explain a few things to me?

How do I use the output of this script and enter it into earth-reverse-engineering? I have the bounding box of a building I want a model for and I'm not really sure how to use the output in earth-reverse-engineering.

What do the levels mean? For example: ```node dump_obj.js 20527061605273514 20 ``` what does specifying the max level here mean?

**Comment by psociety** [comment]
Level is the zoom, go to google maps and zoom in, you will see how a z var changes in the url. It obviously has a max zoom and not all areas have the same.
